# Generated by Django 4.2.1 on 2023-09-05 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_alter_shopitem_imageitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='shopitem',
            name='available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home_page.category'),
        ),
    ]
