# Generated by Django 4.2.1 on 2023-09-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='category',
        ),
        migrations.AddField(
            model_name='shopitem',
            name='category',
            field=models.ManyToManyField(to='home_page.category'),
        ),
    ]
