# Generated by Django 4.2.1 on 2023-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_category_category_remove_shopitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='shopitem',
            name='brand',
            field=models.ManyToManyField(to='home_page.brand'),
        ),
    ]
