# Generated by Django 4.2.1 on 2023-09-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_brand_shopitem_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='prefer',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
