# Generated by Django 4.2.1 on 2023-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0007_shopitem_prefer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='on_chart',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
