# Generated by Django 4.2.1 on 2023-09-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0008_shopitem_on_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
